### ISSUE TITLE
graph_models data should not encoding

### ISSUE THREAD

**Issue by kmollee** [django-extensions/django-extensions#531] opened 2014-08-07 01:53 UTC
I use python 3.4 django 1.7

try to use pygraphviz and graph_models, have a lot problem

finally find out what cause all of problem.

in `django_extensions/management/commands/graph_models.py` line 128

in `render_output_pygraphviz` function
variable dotdata use bytes type, not string type

also find out in line 76, encoding dotdata 

`pygraphviz.AGraph` class accept string not the bytes

my soultion is just don't encoding the dotdata
```
# orig in line 76
        dotdata = dotdata.encode('utf-8')
# after ... just delete the line

```

hope it can help have same issue people

**Comment by dsent** [comment] 2015-01-18 22:06
I have the same issue with Python 3.4.2/Django 1.7.3/django-extensions 1.4.9/pygraphviz 1.3rc2.
Worked around it by decoding dotdata back to utf-8:
`graph = pygraphviz.AGraph(dotdata.decode('utf-8'))`

**Comment by trbs** [comment] 2015-01-19 12:16
Both ```pygraphviz``` and ```pydot``` stable do not install for me on Python3.4 (osx)

```pygraphviz-1.3rc2``` also does not work for me on osx. Only the github version works.

So I was only able to test with the github version of pygraphviz and I can also confirm that not encoding works for Python3.

I've committed a patch that will not encode the dotdata with Python 3.x

Please check the patch.

**Comment by trbs** [comment] 2015-01-22 23:37
Please reopen if there are still issues.

**Closed by trbs** 2015-01-22 23:37 UTC
Labels: bug, need help, need patch, need test case

**Comment by dsent** [comment] 2015-01-23 08:00
The patch looks right.
I use Anaconda distribution and don't want to cause a mess in my environment by installing something manually, but I'll test if the problem is gone in the next version of the module available through PyPI.

**Comment by trbs** [comment] 2015-01-23 10:09
I understand, I'm hoping to do a new release this weekend.
