### ISSUE TITLE
Can't setup environment for development

### ISSUE THREAD

**Issue by chrishna1** [django-extensions/django-extensions#1582] opened 2020-09-10 18:01 UTC
I am just trying to contribute to the tests. I started to run `make test` command. It gives me the following error.

OS: `Ubuntu18.04.4 LTS`

Here's the relevant stack trace: 

```bash
Using /mnt/c/Users/insol/Workspace/OSS/django-extensions/.eggs/coverage-5.2.1-py3.6-linux-x86_64.egg

Traceback (most recent call last):
  File "setup.py", line 183, in <module>
    'Topic :: Utilities',
  File "/mnt/c/Users/balakrishnaj/Workspace/venvs/django_extensions/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/mnt/c/Users/balakrishnaj/Workspace/venvs/django_extensions/lib/python3.6/site-packages/setuptools/command/test.py", line 214, in run
    installed_dists = self.install_dists(self.distribution)
  File "/mnt/c/Users/balakrishnaj/Workspace/venvs/django_extensions/lib/python3.6/site-packages/setuptools/command/test.py", line 206, in install_dists
    tr_d = dist.fetch_build_eggs(dist.tests_require or [])
  File "/mnt/c/Users/balakrishnaj/Workspace/venvs/django_extensions/lib/python3.6/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
    replace_conflicting=True,
  File "/mnt/c/Users/balakrishnaj/Workspace/venvs/django_extensions/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pluggy 1.0.0.dev0 (/mnt/c/Users/balakrishnaj/Workspace/Learning/OSS/django-extensions/.eggs/pluggy-1.0.0.dev0-py3.6.egg), Requirement.parse('pluggy<1.0,>=0.12'), {'pytest'})
Makefile:38: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by abhiabhi94** [comment] 2020-09-11 09:10
I'm also facing the same issue:

`OS: Ubuntu18.04.4 LTS`
`Python: 3.8`

I was trying to set up the project for development and contribute to one of the issues. I thought running `make test` would itself install all the requirements.

**What I did**

Forked this repository and executed the following command:

```bash

$ git clone git@github.com:abhiabhi94/django-extensions.git

$ python3.8 -m venv ~/.virtualenvs/django-extensions
$ source ~/.virtualenvs/django-extensions/bin/activate
(django-extensions)$ cd django-extensions
(django-extensions)$ pip install -e ../django-extensions
(django-extensions)$ make test

```

The stack trace is similar to the one mentioned above. From it what I could see is there is some version conflict with `pluggy` which requires a `version >=0.12` and `version < 1.0` but it is getting version `1.0.0.dev0`. I'm not really sure where this arises from since I couldn't really find it inside `setup.py`.

The packages installed currently inside the virtual environment are:
```bash

(django-extensions) $ pip freeze
-e git+git@github.com:abhiabhi94/django-extensions.git@0488b46f30db0e51b375bedbc035ee4ba60c8005#egg=django_extensions
pkg-resources==0.0.0    #  debian specific bug 

```

I'm willing to put forward a pull request to handle this and add instructions for setting up if I get to know how to solve this. Any help or suggestions would be great.

**Comment by trbs** [comment] 2020-09-11 10:17
Interesting...

This works flawlessly on macOS with Python 3.8.5.
It also works flawlessly on Ubuntu 19.10 Python 3.7.5 as long as I first `pip install wheel` or`pip install U pip setuptools` before `make test`, otherwise I get an error about missing `bdist_wheel`.

Using the following to test
```
$ cd /tmp
$ python3 -m venv venv  # installed Python 3.8 on macOS and 3.7 on Ubuntu box for me.
$ git clone https://github.com:django-extensions/django-extensions.git
```

**Comment by trbs** [comment] 2020-09-11 10:26
This seems hard to reproduce for me, assuming this is because the issue is triggered by specific enviroments like `Ubuntu18.04.4 LTS`...

Besides that I actually never use the `Makefile` directly anymore... normally everything goes through `tox`. 

Could you guys try with: `$ tox -e dj31` ?  (or more specific with a python version like `$ tox -e py38-dj31`)
Seeing if that errors out as well ?

I already planned (but was always on the back-burner) to remove our usage of `python ./setup.py test` and just use `pytest`  and `tox` directly also removing the `Makefile` in the process (or at the very least updating that to match).

**Comment by abhiabhi94** [comment] 2020-09-11 10:40
Hey @trbs, I firstly installed wheel and tried to run `make test` which again failed.

Then I updated `pip` and reran the tests using` `tox` and it worked fine.

I'm not sure if the tox command could have worked without installing `wheel` or upgrading `pip`.

Also, what else if any should I do to install all the requirements for me to start working on the project?

**Comment by trbs** [comment] 2020-09-11 11:51
> Also, what else if any should I do to install all the requirements for me to start working on the project?

This is not the problem right ?
As for me on both macOS and Ubuntu just running `make test` in a venv just-works(tm).

I can replace this issue with Ubuntu18.04.4 LTS in Docker.

**Comment by abhiabhi94** [comment] 2020-09-11 12:04
> This is not the problem right ?

yes it is currently. I thought running the tests might install the dependencies required but it installed everything using `eggs`. i belienve for me to be able to work on the project, i need to run the `test_app` but i couldn't any requirements file. hence ended up asking.

**Comment by trbs** [comment] 2020-09-11 12:25
> > This is not the problem right ?
> 
> yes it is currently. I thought running the tests might install the required dependencies inside the `virtualenv` but it installed everything inside `.eggs`. i believe for me to be able to work on the project, i need to run the `testapp` but i couldn't find any requirements file. hence ended up asking.

Sorry the reply got submitted before I finished typing it :-)

I think it's not the root cause since it is supposed to work that way and actually does work this way on other OS & Python combinations... The issue seems to be something broken in those environments when `setup.py` installs the requirements from `tests_require` vs if you manually install them.

Anyways typing the reply I already rewrote most of what I was planning anyways... should have a commit soon for you guys to try out.

**Comment by trbs** [comment] 2020-09-11 13:08
Please take a look at: https://github.com/django-extensions/django-extensions/commit/9ca3e36efca38764c1bca28d188c77f91e49e64a

```bash
$ python3 -m venv venv
$ source venv/bin/activate
$ cd django-extensions
$ pip install django -e . -r requirements-dev.txt
$ pytest
```

For now I did not add `django` to `setup.py` `install_required` since I remember there where issues with that in the past so we still need to install Django separately...

Please check if this is working better for you guys...
Also if somebody wants to take a stab at a PR for a `developer.rst` or `contributions.rst` that would be much appreciated ;-)

**Comment by abhiabhi94** [comment] 2020-09-11 14:52
Yes it seems to be working. Thanks

I think I do understand why adding `Django` to requirements would create issues because it would interfere with the environments created with specific `django` versions. 

One option that i can think of currently, is to copy and paste the dependencies here and then add `django` to `requirements-dev.txt`. I'm not sure this is the most elegant solution but should work.

If you are okay with, I'll make a separate pull request for this one.

**Comment by abhiabhi94** [comment] 2020-09-11 16:28
Do I also need to run some command to laod test data?

I ran `migrate` command but it obviously doesn't work because it has been specified in the settings as a `memory` based database.

I also added this line inside `testapp/settings.py`:

```python

from django.core.management import execute_from_command_line

execute_from_command_line(['./manage.py', 'migrate'])

```
which allows the migration command to be run automatically when the server starts. 

After restarting the server, it still doesn't help because it can't find the tables `django_sites` or `django_session`. Do I need to create my own data or run a command to load data?

**Comment by trbs** [comment] 2020-09-11 16:58
> Do I also need to run some command to laod test data?

Sorry I do not think I fully understand... why would you want to do that ?
Do you mean that your hitting the fact that our test suite does not have migration files ?

You can just use `pytest`, like:
```python
$ pytest tests/test_sqldiff.py -v --no-cov
=========================================================== test session starts ============================================================
platform darwin -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /Users/trbs/Projects/django-extensions/venv/bin/python3
cachedir: .pytest_cache
django: settings: tests.testapp.settings (from ini)
rootdir: /Users/trbs/Projects/django-extensions, configfile: setup.cfg
plugins: Faker-4.1.1, django-3.9.0, cov-2.10.0
collected 7 items

tests/test_sqldiff.py::SqlDiffTests::test_format_field_names PASSED                                                                  [ 14%]
tests/test_sqldiff.py::SqlDiffTests::test_invalid_mysql_to_dict SKIPPED                                                              [ 28%]
tests/test_sqldiff.py::SqlDiffTests::test_mysql_to_dict SKIPPED                                                                      [ 42%]
tests/test_sqldiff.py::SqlDiffTests::test_postgresql_to_dict SKIPPED                                                                 [ 57%]
tests/test_sqldiff.py::SqlDiffTests::test_sql_diff_with_proxy_models PASSED                                                          [ 71%]
tests/test_sqldiff.py::SqlDiffTests::test_sql_diff_without_proxy_models PASSED                                                       [ 85%]
tests/test_sqldiff.py::SqlDiffTests::test_sqlite_to_dict PASSED                                                                      [100%]

======================================================= 4 passed, 3 skipped in 1.10s =======================================================
```

Anythings else you want is up to you...

For example the following is completely possible:
```python
(venv) $ export DJANGO_EXTENSIONS_DATABASE_NAME="db.sqlite3"
(venv) $  ./manage.py migrate --run-syncdb
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, sites
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
(venv) $ ./manage.py shell_plus
# Shell Plus User Pre Imports
import sys, os
# Shell Plus Model Imports
from django.contrib.admin.models import LogEntry
from tests.collisions.models import Group, SystemUser, UniqueModel
from tests.testapp.models import AbstractInheritanceTestModelChild, ChildSluggedTestModel, Club, CustomFuncPrecedenceSluggedTestModel, CustomFuncSluggedTestModel, CustomModelModificationDateTimeField, DisabledUpdateModelModificationDateTimeField, DummyRelationModel, FKSluggedTestModel, FKSluggedTestModelCallable, FunctionSluggedTestModel, HasOwnerModel, InheritedFromPostWithUniqField, InheritedFromPostWithUniqFieldCompat, JSONFieldTestModel, Membership, ModelMethodSluggedTestModel, ModelModificationDateTimeField, MultipleFieldsAndMethods, Name, Note, OverridedFindUniqueModel, Permission, Person, Personality, Photo, Post, PostWithTitleOrdering, PostWithUniqField, PostWithUniqFieldCompat, RandomCharTestModel, RandomCharTestModelAlpha, RandomCharTestModelAlphaDigits, RandomCharTestModelDigits, RandomCharTestModelLowercase, RandomCharTestModelLowercaseAlphaDigits, RandomCharTestModelPunctuation, RandomCharTestModelUnique, RandomCharTestModelUniqueTogether, RandomCharTestModelUppercase, RandomCharTestModelUppercaseAlphaDigits, ReverseModel, ReverseModelCompat, SecondDummyRelationModel, Secret, ShortUUIDTestAgregateModel, ShortUUIDTestManyToManyModel, ShortUUIDTestModel_field, ShortUUIDTestModel_pk, SluggedTestModel, SluggedTestNoOverwriteOnAddModel, SluggedWithConstraintsTestModel, SluggedWithUniqueTogetherTestModel, SqlDiff, SqlDiffUniqueTogether, ThirdDummyRelationModel, TimestampedTestModel, UnicodeVerboseNameModel, UniqueTestAppModel
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
from django.contrib.sites.models import Site
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When
from django.utils import timezone
from django.urls import reverse
from django.db.models import Exists, OuterRef, Subquery
# Shell Plus User Imports
from django_extensions import settings as django_extensions_settings
# Shell Plus User Post Imports
import traceback
import pprint
import os as test_os
from django_extensions.utils import *
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: Post(title="hello world").save()
Out[1]: <Post: Post object (None)>

In [2]: Post.objects.all()
Out[2]: <ActivatorQuerySet [<Post: Post object (1)>]>
```

Note the `--run-syncdb` on `migrate` :-)

While this works (and I use it in the development of Django Extensions) please do understand that this is not really supported in the sense that I do not plan to answer extensive support questions on this type of stuff.... for that you or your company can hire me ;-) as it's outside of the scope of `Django Extensions`.

That said I am very happy and willing to merge a PR improving the documentation with this kind of information, so other people can learn from it ;-)

**Comment by trbs** [comment] 2020-09-11 17:00
> Yes it seems to be working. Thanks
> 
> I think I do understand why adding `Django` to requirements would create issues because it would interfere with the environments created with specific `django` versions.
> 
> One option that i can think of currently, is to copy and paste the dependencies in `tox.ini` and then add `django` to `requirements-dev.txt`. I'm not sure this is the most elegant solution but should work.
> 
> If you are okay with, I'll make a separate pull request for this one.

If you have a real elegant and full-proof solution I'm happy to merge it... but I will say I will be very conservative with any PR... since it's not really a big issue during development and I do not want to break stuff..

Maybe the new dependency resolver of `pip` could help solve this issue in an elegant way ? (not sure)

**Comment by abhiabhi94** [comment] 2020-09-11 17:22
> Sorry I do not think I fully understand... why would you want to do that ?

I was excepting the `testapp` to have some dummy data as some other libraries do. No issues, I think setting the environment variable for database helped me go through the GUI part.

> While this works (and I use it in the development of Django Extensions) please do understand that this is not really supported in the sense that I do not plan to answer extensive support questions on this type of stuff.... for that you or your company can hire me ;-) as it's outside of the scope of Django Extensions.

Sorry to bother you. I do understand your time is precious. I wanted to work on the issue #1530 and wanted to set up the development environment for it. I do understand almost all the stuff that `django-extensions` adds is through command line hence it can be run without having to provide any data for the `testapp`. No issues I will try to finish the work soon and put together a pull request as soon as I can.

**Comment by trbs** [comment] 2020-09-11 20:09
No worries any help is much appreciated !

If you want and have a few spare cycles creating a small write-up for other developers (in the docs) would be really cool ;-)

I also hope the latest changes help make development a bit easier... (I certainly like that `pytest` works like any other project out of the box now ;-) )

For now I will close this issue, we can continue the conversation here on the dev environment if there any things that do not work properly with my latest commits, no issues.

Thanks for helping out !

**Closed by trbs** 2020-09-11 20:09 UTC
