### ISSUE TITLE
SyntaxError: invalid syntax in dumpscript

### ISSUE THREAD

**Issue by martinvol** [django-extensions/django-extensions#1230] opened 2018-08-02 01:34 UTC
After generating a dumpscrip, I called it somewhere else and I got a syntax error. I'm aware this is not the way the documentation suggest for running the script, but the syntax error shouldn't be there anyway, I didn't try but it would also fail doing `./manage.py runscript out`

`python out.py`

```
  File "out.txt", line 136
    pictures_picture_3.owner_user =  importer.locate_object(User, "id", User, "id", 1, {'id': 1, 'password': 'XXXX', 'last_login': datetime.datetime(2018, 7, 30, 3, 19, 37, 885214, tzinfo=<UTC>), 'is_superuser': True, 'first_name': 'Martín', 'last_name': 'Volpe', 'is_staff': True, 'is_active': True, 'date_joined': datetime.datetime(2010, 1, 11, 21, 45, 36, tzinfo=<UTC>), 'email': 'XX@gmail.com', 'slug': 'martinvol'} )
                                                                                                                                                   ^
SyntaxError: invalid syntax

```

The error is with `tzinfo=<UTC>`

Django 2.0.7
django-extensions 2.0.7
Pyton 3.6.4

If you are struggling with the error yourself, you can walk around generating the user manually (if it doesn't exist yet) and replace 

`owner_user =  importer.locate_object(User, "id", User, "id", 1, {'id': 1, 'password': 'XXXX', 'last_login': datetime.datetime(2018, 7, 30, 3, 19, 37, 885214, tzinfo=<UTC>), 'is_superuser': True, 'first_name': 'Martín', 'last_name': 'Volpe', 'is_staff': True, 'is_active': True, 'date_joined': datetime.datetime(2010, 1, 11, 21, 45, 36, tzinfo=<UTC>), 'email': 'XX@gmail.com', 'slug': 'martinvol'} ) `

with:

`owner_user =  User.objects.get(email='XX@gmail.com')`

Best,

**Comment by trbs** [comment] 2018-08-02 11:29
Seems an error in serializing those datetime's. In other places it's serialized as:
```
"dateutil.parser.parse(\"%s\")" % value.isoformat()
```

This is probably the best way to do it here as well.

You think you can create a PR for this or at least a PR that creates a test in the testsuite that fails on the current behavior ? (eg: asserting that the output does not contain <UTC>)

**Comment by the-bionic** [comment] 2018-09-05 12:46
Happy to pick this up as a new contributor.

**Comment by trbs** [comment] 2018-09-05 21:45
@the-bionic awesome ! I hope @martinvol can help create a reproducible test case.

**Comment by bravetheheat** [comment] 2018-10-12 03:43
Having this error as well.

**Comment by martinvol** [comment] 2018-10-12 03:50
Sorry I didn't follow this up. I will work on writing the needed tests in
the next couple of weeks.

**Comment by mristroph** [comment] 2019-05-30 18:16
I consider this a bug in `pytz`, not `django-extensions`. Root cause here is that `repr(pytz.utc)` is "<UTC>", which can't be eval'ed.

See here: https://bugs.launchpad.net/pytz/+bug/1709127

**Comment by yeojin-dev** [comment] 2019-11-25 05:38
Could you close this issue? I fixed. :) @trbs

**Closed** 2019-12-05 08:48 UTC
Labels: Easy Pickings, bug, need patch
