### ISSUE TITLE
Autogenerated SSL certificate too weak

### ISSUE THREAD

**Issue by michela** [django-extensions/django-extensions#1162] opened 2018-02-20 08:56 UTC
Using django-extensions 1.9.9 you get SSL error that autogenerated cert is too weak.

Workaround, manually creating cert, documented here

https://www.reddit.com/r/django/comments/2jbs45/django_runserver_plus_with_ssl_and_firefox_33/

**Comment by trbs** [comment] 2018-02-21 19:52
Link: https://github.com/pallets/werkzeug/issues/611

**Comment by trbs** [comment] 2018-02-21 19:57
I cannot reproduce this... when I run:

`./manage.py runserver_plus --cert=/tmp/temporary.cert`

On latest `Django-Extensions`, `Werkzeug`, `Django` and `Python` and `Firefox` I need to accept the self-signed certificate and then all works fine.

Could you check the versions you are using ? 
(Since this should be fixed in Werkzeug as of 0.10)

Please submit a PR to enforce using a minimum version of `werkzeug` that creates the right certificates.

**Closed by trbs** 2018-02-21 19:57 UTC
