### ISSUE TITLE
Use of option_list in Commands triggers deprecation warning in Django 1.9

### ISSUE THREAD

**Issue by jonblum** [django-extensions/django-extensions#770] opened 2015-12-03 17:06 UTC
Running `runserver_plus.py` and most other django-extensions commands produces the following deprecation warning:
```
11:26:59 web.1  | WARNING  [py.warnings:265] {snip}/lib/python2.7/site-packages/django/core/management/base.py:265:
RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
```

[The docs](https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/#django.core.management.BaseCommand.option_list) advise using `add_arguments` in its place:
> You should now override the add_arguments() method to add custom arguments accepted by your
> command. See the example above.

This will be breaking in Django 1.10.

**Comment by thecardcheat** [comment] 2016-01-18 23:31
Duplicate of #788?

**Closed** 2016-01-19 00:30 UTC
Labels: need help, need patch
