### ISSUE TITLE
Error on upgrading to 2.1.0: unqualified exec is not allowed in function 'get_plain'

### ISSUE THREAD

**Issue by clokep** [django-extensions/django-extensions#1219] opened 2018-07-17 12:00 UTC
After upgrading from 2.0.7 to 2.1.0 on a Django 1.11.x project on Python 2.7.x I get the following error when running `python manage.py shell_plus`:

```
$ python manage.py shell_plus
Traceback (most recent call last):
  File "manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/my_venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/my_venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/my_venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/my_venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/my_venv/local/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 283
    exec(compile(pythonrc_code, pythonrc, 'exec'), imported_objects)
SyntaxError: unqualified exec is not allowed in function 'get_plain' it contains a nested function with free variables
```

Not sure what's happening, but I confirmed everything is working OK after downgrading back to 2.0.7! Any thoughts would be appreciated!

**Comment by trbs** [comment] 2018-07-27 13:38
Can you confirm your using Python < 2.7.9 ?

**Comment by clokep** [comment] 2018-07-27 13:56
Yes, I'm on Ubuntu 14.04, so using Python 2.7.6.

**Comment by belugame** [comment] 2018-09-03 05:26
Same for us on Django 1.11/Python 2.7.6

**Comment by ThibaultLemaire** [comment] 2018-11-22 09:03
For the record, #1091 first mentioned this bug, which was then fixed by #1102, and then roll-backed by https://github.com/django-extensions/django-extensions/commit/50a0e4ccd88be5186bc3282307e7e51169865d79 released in [2.0.8](https://github.com/django-extensions/django-extensions/releases/tag/2.0.8).

Therefore, for anybody still having this issue, the last useable version of django-extensions, is indeed [2.0.7](https://github.com/django-extensions/django-extensions/releases/tag/2.0.7).

**Comment by furlongm** [comment] 2019-07-20 17:08
This issue also occurs on RHEL 7 / CentOS 7, with the default python installed (Python 2.7.5) and Django 1.11.

Applying the patch from fc963b7211acf5404c8737fcb8f080701bcfca85 fixes the issue.

Downgrading to 2.0.7 also works.

Could the compatibility patch be re-applied? It seems to fix the issue on a number of platforms.

**Comment by trbs** [comment] 2019-07-21 21:06
It's a shame vendors won't patch their Python packages fixing the bug in Python leaving this up to the maintainers to deal with the mess :-(

I'm happy to merge any patch that passes tests and does not cause any other regressions. Since Django 1.11 and Python 2.7 are still supported until April 2020.

Let's see if we can fix the tests on the PR and make sure the tests actually cover every other installation as well to make sure we don't regress somewhere else.

**Comment by trbs** [comment] 2020-01-04 23:42
I wonder how large the impact of this still is.

As mentioned before and in https://github.com/django-extensions/django-extensions/pull/1397 I think any fix for this would need to proof that it does not break any other installation.

For now I will close this issue. If this is still an issue for people and there is a proper solution possible we can always reopen.

**Closed by trbs** 2020-01-04 23:42 UTC
Labels: food for thought
