### ISSUE TITLE
show_urls UnicodeEncodeError

### ISSUE THREAD

**Issue by ynikitenko** [django-extensions/django-extensions#650] opened 2015-03-29 10:40 UTC
When running 

$ python manage.py show_urls

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django_extensions/management/utils.py", line 71, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django_extensions/management/commands/show_urls.py", line 141, in handle
    decorator=', '.join(decorators),
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-12: ordinal not in range(128)

Python 2.7.5.
Django (1, 6, 10, 'final') works fine. coding is written in my urls.py . 
django-extensions Version: 1.5.2

Sorry, I don't know what this bug really belongs to (whether that is my or django's issue, not django-extensions) and where it would be better to submit that - I couldn't find that in the documentation.

**Comment by avichalp** [comment] 2015-09-22 16:53
Hi, 

Does any know how to reproduce this bug? It is working fine for me.

**Comment by ynikitenko** [comment] 2015-11-22 12:13
I've received your comment notification, but now I can't reproduce that - probably because of different setup.
> $python manage.py show_urls
> Unknown command: 'show_urls'
My django version is also different now, '1.8.6'. But if needed, I can try to reproduce that.

**Comment by navyad** [comment] 2016-08-16 17:02
working fine for me as well.

```
django-extensions==1.6.7
Django==1.9.6
```

**Comment by trbs** [comment] 2016-08-16 20:04
Thanks everybody.

Closing it now because it seems to be fixed.

**Closed by trbs** 2016-08-16 20:04 UTC
Labels: bug, Easy Pickings, need patch, need test case
