### ISSUE TITLE
sqldiff KeyError: u'id'

### ISSUE THREAD

**Issue by rubic** [django-extensions/django-extensions#587] opened 2014-12-13 21:29 UTC
I upgraded to django-extensions 1.4.8 via pip and encountered the following error using sqldiff:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "./local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "./local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "./local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 1003, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "./local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "./local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 987, in execute
    super(Command, self).execute(*args, **options)
  File "./local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "./local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 980, in handle
    sqldiff_instance.find_differences()
  File "./local/lib/python2.7/site-packages/django/db/transaction.py", line 399, in inner
    return func(*args, **kwargs)
  File "./local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 509, in find_differences
    self.find_unique_missing_in_db(meta, table_indexes, table_constraints, table_name)
  File "./local/lib/python2.7/site-packages/django_extensions/management/commands/sqldiff.py", line 312, in find_unique_missing_in_db
    db_field_unique = table_indexes[attname]['unique']
KeyError: u'id'
```

Environment: Python 2.7, Django 1.6

**Comment by trbs** [comment] 2015-01-05 17:16
That is so weird.. since 1.3.6 only bumped the version number..

Would it be possible to post the code and maybe fixtures ?

**Comment by kurevin** [comment] 2015-03-12 18:41
Can't reproduce the issue. I did not checked what exactly fixed it for me, project changes or updated version of django-extensions.

**Comment by trbs** [comment] 2015-03-17 06:53
I'll close it for now. If it happens again please open a new ticket.

**Closed by trbs** 2015-03-17 06:53 UTC
Labels: bug, Easy Pickings, need help, need patch
