### ISSUE TITLE
./manage.py admin_generator: error: unrecognized arguments: ... and some exceptions...

### ISSUE THREAD

**Issue by prokher** [django-extensions/django-extensions#820] opened 2016-02-02 22:24 UTC
I would like to generate admin interface for my apps. First I run:
```bash
> ./manage.py admin_generator
This command requires an existing app name as argument
Available apps:
    apps.portal.api
    debug_toolbar
    django.contrib.admin
    django.contrib.auth
    django.contrib.contenttypes
    django.contrib.sessions
    django_extensions
    rest_framework
```

Here I see the list of apps and try to generate_admin for one of them:
```bash
> ./manage.py admin_generator apps.portal.api
usage: manage.py admin_generator [-h] [--version] [-v {0,1,2,3}]
                                 [--settings SETTINGS]
                                 [--pythonpath PYTHONPATH] [--traceback]
                                 [--no-color] [-s SEARCH_FIELD]
                                 [-d DATE_HIERARCHY] [-p PREPOPULATED_FIELDS]
                                 [-l LIST_FILTER_THRESHOLD]
                                 [-r RAW_ID_THRESHOLD]
manage.py admin_generator: error: unrecognized arguments: apps.portal.api
```

I thought I did something wrong and run
```bash
> ./manage.py admin_generator --help
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/prokher/Dev/PyVirtEnvs/pSeven/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/prokher/Dev/PyVirtEnvs/pSeven/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/prokher/Dev/PyVirtEnvs/pSeven/lib/python3.4/site-packages/django/core/management/base.py", line 339, in run_from_argv
    options = parser.parse_args(argv[2:])
  File "/home/prokher/Dev/PyVirtEnvs/pSeven/lib/python3.4/site-packages/django/core/management/base.py", line 59, in parse_args
    return super(CommandParser, self).parse_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1737, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1769, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1975, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.4/argparse.py", line 1915, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.4/argparse.py", line 1843, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.4/argparse.py", line 1025, in __call__
    parser.print_help()
  File "/usr/lib/python3.4/argparse.py", line 2368, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.4/argparse.py", line 2352, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.4/argparse.py", line 287, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.4/argparse.py", line 217, in format_help
    func(*args)
  File "/usr/lib/python3.4/argparse.py", line 217, in format_help
    func(*args)
  File "/usr/lib/python3.4/argparse.py", line 524, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib/python3.4/argparse.py", line 611, in _expand_help
    return self._get_help_string(action) % params
TypeError: %d format: a number is required, not dict
```
and that is why I am here posting the issue :)

I use Django 1.9.2 and django-extensions installed with ```pip install git+https://github.com/django-extensions/django-extensions --upgrade```

**Comment by marctc** [comment] 2016-02-18 09:04
The problem is that if we are working with Django >= 1.8 the default formatter on `help` argument needs to be written `[default: %(default)s]` instead of `[default: %default]` which actually causes the above issue see ([argparse documentation](https://docs.python.org/3/library/argparse.html#upgrading-optparse-code)) .

However, if we change all the options with `[default: %(default)s]` formatter it won't see properly on Django < 1.8:
```
  -s SEARCH_FIELD, --search-field=SEARCH_FIELD
                        Fields named like this will be added to
                        `search_fields` [default: %(default)s]
```
So, `CompatibilityBaseCommand` needs to be fixed in order to solve this problem. I've trying to figure out this problem for a while, but I can't see any easy solution right now. Maybe @thecardcheat  can help us so he was the responsible to fix compatibility between Django versions.

**Comment by thecardcheat** [comment] 2016-02-18 16:19
Thanks for identifying the issue clearly and linking to those docs (hadn't seem them). I think there is a sensible location to resolve this and I should be able to submit a PR.

**Comment by marctc** [comment] 2016-02-18 16:31
Thanks @thecardcheat.  Hope you find out the solution without lose to much time. Let me know if you need help.

**Comment by marctc** [comment] 2016-05-31 08:10
@trbs this issue can be closed.

**Comment by trbs** [comment] 2016-06-13 12:14
Thanks

**Closed by trbs** 2016-06-13 12:14 UTC
