### ISSUE TITLE
ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by lwm** [django-extensions/django-extensions#881] opened 2016-05-03 09:53 UTC
So, I installed `django-extensions` from Github with:

```
pip install -e git+https://github.com/django-extensions/django-extensions.git@4e9989efac51f562b6ec9827095cd4012d2b0ebf#egg=django-extensions
```

Then got the following:

```
$ ./manage.py graph_models -a
INFO:root:settings.ENVIRONMENT: dev
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/lwm/work/lock8/velodrome/.venv/src/django-extensions/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/home/lwm/work/lock8/velodrome/.venv/src/django-extensions/django_extensions/management/commands/graph_models.py", line 147, in handle
    graph_data = generate_graph_data(args, cli_options=cli_options, **options)
  File "/home/lwm/work/lock8/velodrome/.venv/src/django-extensions/django_extensions/management/modelviz.py", line 269, in generate_graph_data
    add_relation(field, '[arrowhead=none, arrowtail=none, dir=both]')
  File "/home/lwm/work/lock8/velodrome/.venv/src/django-extensions/django_extensions/management/modelviz.py", line 241, in add_relation
    target_model = get_model(field.rel.to)
  File "/home/lwm/work/lock8/velodrome/.venv/src/django-extensions/django_extensions/compat.py", line 208, in get_model
    return apps.get_model(*path.split('.', 1))
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/apps/registry.py", line 196, in get_model
    app_label, model_name = app_label.split('.')
ValueError: not enough values to unpack (expected 2, got 1)
```

I have a field defined as:

```
foo = models.OneToOneField('Bar', related_name='+', on_delete=models.SET_NULL, blank=True, null=True)
```

Then the code which deals with lazy relationships (`modelviz.py`) blows up:

```
                # handle self-relationships and lazy-relationships
                if isinstance(field.rel.to, six.string_types):
                    if field.rel.to == 'self':
                        target_model = field.model
                    else:
                        # the following line fails due to `field.rel.to` being `Bar` and not `app_label.Bar` 
                        target_model = get_model(field.rel.to)
                else:
                    target_model = field.rel.to
```

Not really sure what to do there.

**Comment by blueyed** [comment] 2016-05-03 12:35
The problem is that `field.rel.to` only has the model, not the app label.  Using `app.Bar` instead of `Bar` (as a string) works around this.
I think I have a fix for this, PR will follow.

**Comment by lwm** [comment] 2016-05-03 12:47
> Using app.Bar instead of Bar (as a string) works around this. 

Yep, that's what I also got. Nice one on the fix!

**Closed** 2016-05-03 13:18 UTC

**Comment by trbs** [comment] 2016-05-03 13:20
Thanks for the report and (bug)fix !

If anybody can create a PR with tests for this issue so that we don't have a regression on this in the future it would be much appreciated :)
