### ISSUE TITLE
Model imports shown, but giving NameError on usage.

### ISSUE THREAD

**Issue by noodlebreak** [django-extensions/django-extensions#1499] opened 2020-03-08 07:41 UTC
Version:
- django-extensions==2.2.8
- Django==3.0.2
- ipython==7.13.0

Sample output:

```python
 (2004)-> ./manage.py shell_plus --ipython
[TerminalIPythonApp] WARNING | File not found: '/home/ash/.pythonrc'
# Shell Plus Model Imports
from allauth.account.models import EmailAddress, EmailConfirmation
from allauth.socialaccount.models import SocialAccount, SocialApp, SocialToken
from catalogue.models import Brand, Category, Product, ProductImage
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
from django.contrib.sites.models import Site
from orders.models import LineItem, Order, Review
from rest_framework.authtoken.models import Token
from users.models import User
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When, Exists, OuterRef, Subquery
from django.utils import timezone
from django.urls import reverse
Python 3.8.2 (default, Feb 26 2020, 04:23:39) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.
[TerminalIPythonApp] WARNING | File not found: '/home/ash/.pythonrc'

In [1]: User                                                                                                                    
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-1974857568df> in <module>
----> 1 User

NameError: name 'User' is not defined
```

Also, in my settings I already have this:

```python
    # Custom user app
    AUTH_USER_MODEL = 'users.User'
```

```python
# settings/local.py
    INSTALLED_APPS += ('django_nose', 'django_extensions',)
```

**Comment by trbs** [comment] 2020-03-08 14:18
Also see https://github.com/django-extensions/django-extensions/issues/1496

Similar to the other report I cannot reproduce this :( (see below)

If you could make a reproducible test case / gist that would be most helpful.

```
$ ./manage.py shell_plus
# Shell Plus Model Imports
from django.contrib.admin.models import LogEntry
from tests.collisions.models import Group, SystemUser, UniqueModel
from tests.testapp.models import AbstractInheritanceTestModelChild, ChildSluggedTestModel, Club, CustomFuncPrecedenceSluggedTestModel, CustomFuncSluggedTestModel, CustomModelModificationDateTimeField, DisabledUpdateModelModificationDateTimeField, DummyRelationModel, FKSluggedTestModel, FKSluggedTestModelCallable, FunctionSluggedTestModel, HasOwnerModel, InheritedFromPostWithUniqField, JSONFieldTestModel, Membership, ModelMethodSluggedTestModel, ModelModificationDateTimeField, Name, Note, OverridedFindUniqueModel, Permission, Person, Personality, Photo, Post, PostWithTitleOrdering, PostWithUniqField, RandomCharTestModel, RandomCharTestModelAlpha, RandomCharTestModelAlphaDigits, RandomCharTestModelDigits, RandomCharTestModelLowercase, RandomCharTestModelLowercaseAlphaDigits, RandomCharTestModelPunctuation, RandomCharTestModelUnique, RandomCharTestModelUniqueTogether, RandomCharTestModelUppercase, RandomCharTestModelUppercaseAlphaDigits, ReverseModel, SecondDummyRelationModel, Secret, ShortUUIDTestAgregateModel, ShortUUIDTestManyToManyModel, ShortUUIDTestModel_field, ShortUUIDTestModel_pk, SluggedTestModel, SluggedTestNoOverwriteOnAddModel, SluggedWithConstraintsTestModel, SluggedWithUniqueTogetherTestModel, SqlDiff, SqlDiffUniqueTogether, ThirdDummyRelationModel, TimestampedTestModel, UnicodeVerboseNameModel, UniqueTestAppModel
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
from django.contrib.sites.models import Site
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When, Exists, OuterRef, Subquery
from django.utils import timezone
from django.urls import reverse
Python 3.8.1 (default, Dec 27 2019, 18:06:00)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: User
Out[1]: django.contrib.auth.models.User
```

**Comment by washeck** [comment] 2020-03-31 10:57
We are also seeing this issue in out project. I did not investigate yet what is the cause but there is workaround. If you start shell_plus without ipython (`manage.py shell_plus --plain`) it works.

**Comment by bellini666** [comment] 2020-04-08 14:21
I'm experiencing this issue as well. Like @washeck said, starting a plain shell works, so I'm guessing the problem is in ipython?

**Comment by washeck** [comment] 2020-04-20 16:13
FYI, the problem is gone in our project since we removed `django_nose`. I tried to reproduced the issue in a minimal project with `django_extensions`, `ipython` and `django_nose` but it works as expected so there's something more needed to reproduce the issue.

**Comment by bellini666** [comment] 2020-04-20 17:54
@washeck is right! If I remove `django_nose` from my `INSTALLED_APPS` the issue doesn't happen anymore!

**Comment by trbs** [comment] 2020-04-21 11:19
If you think adding some text to the documentation or even a warning during the startup of `shell_plus` if `django_nose` is detected (and if we know exactly what causes this) I would be happy to merge a PR for this.

Since I guess this might bite more people unexpectedly (and is not so obvious/quick to debug).

**Comment by discover59** [comment] 2020-05-11 13:31
I don't use django_nose at all. And it's still reproducible.
```
Django==2.2.12
iPython==7.13.0
django-extensions==2.2.8
```

**Comment by trbs** [comment] 2020-05-11 13:45
Sadly it is not for me.

On MacOS with Python 3.7.7:

https://gist.github.com/trbs/28f2f45205abb77d94100ee074377651

```
$ cd /tmp
$ python3 -m venv venvtest
$ cd venvtest
$ source bin/activate
$ pip install ipython==7.13.0
...
Successfully installed appnope-0.1.0 backcall-0.1.0 decorator-4.4.2 ipython-7.13.0 ipython-genutils-0.2.0 jedi-0.17.0 parso-0.7.0 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.5 ptyprocess-0.6.0 pygments-2.6.1 six-1.14.0 traitlets-4.3.3 wcwidth-0.1.9
$ pip install Django==2.2.12
...
Successfully installed Django-2.2.12 pytz-2020.1 sqlparse-0.3.1
$ pip install django-extensions==2.2.8
...
Successfully installed django-extensions-2.2.8
$ which django-admin
/private/tmp/venvtest/bin/django-admin
$ django-admin startproject abz
$ cd abz
$ vi abz/settings.py
... add django_extensions to INSTALLED_APPS
$ ./manage.py shell_plus
# Shell Plus Model Imports
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import Group, Permission, User
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When, Exists, OuterRef, Subquery
from django.utils import timezone
from django.urls import reverse
Python 3.7.7 (default, Mar 10 2020, 15:43:33)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: User
Out[1]: django.contrib.auth.models.User

In [2]:
```

So yet it's not possible for me to reproduce 😞 
Apparently there is more going on than it straight up does not work.

I will close this issue for now.

With the kind request to please reopen it after we have a reproducible test case in the form of a git repo, gist or alike.

So this is not a won't fix, we are more happy to fix it, but requested something to reproduce it and as along as that does not exist there is little we can do about it :(

**Closed by trbs** 2020-05-11 13:45 UTC
Labels: Need Reproducable Example, need help, need patch, need test case, needs more information

**Comment by discover59** [comment] 2020-05-11 13:47
```
appdirs==1.4.3
attrs==19.3.0
backcall==0.1.0
beautifulsoup4==4.9.0
black==19.10b0
boto3==1.12.8
botocore==1.15.8
cairocffi==1.1.0
CairoSVG==2.4.2
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
click==7.1.1
colorama==0.4.3
cryptography==2.8
cssselect2==0.2.2
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
dj-database-url==0.5.0
Django==2.2.12
django-dotenv==1.4.2
django-extensions==2.2.8
django-mysql==3.3.0
django-rest-knox==4.1.0
django-rest-passwordreset==1.1.0
djangorestframework==3.11.0
docutils==0.15.2
dropbox==9.4.0
et-xmlfile==1.0.1
gunicorn==20.0.4
html5lib==1.0.1
idna==2.9
ipdb==0.12.3
ipython==7.13.0
ipython-genutils==0.2.0
jdcal==1.4.1
jedi==0.17.0
jmespath==0.9.5
kiwisolver==1.1.0
matplotlib==3.1.3
mysqlclient==1.4.6
numpy==1.18.1
O365==2.0.8
oauthlib==3.1.0
openpyxl==3.0.3
pandas==0.25.3
parso==0.7.0
pathspec==0.7.0
pickleshare==0.7.5
Pillow==7.0.0
prompt-toolkit==3.0.3
psutil==5.7.0
pycparser==2.19
Pygments==2.5.2
pymsteams==0.1.12
pyparsing==2.4.6
Pyphen==0.9.5
python-dateutil==2.8.1
pytz==2019.3
regex==2020.2.20
requests==2.23.0
requests-oauthlib==1.3.0
s3transfer==0.3.3
sentry-sdk==0.14.2
six==1.14.0
soupsieve==2.0
sqlparse==0.3.0
stringcase==1.2.0
stripe==2.43.0
tinycss2==1.0.2
toml==0.10.0
traitlets==4.3.3
typed-ast==1.4.1
tzlocal==2.0.0
urllib3==1.25.8
wcwidth==0.1.8
WeasyPrint==51
webencodings==0.5.1
xlrd==1.2.0
```
Can you please check with this?

**Comment by discover59** [comment] 2020-05-11 13:49
I saw a few other projects with same issue with different package list. Please open the issue again.

**Comment by trbs** [comment] 2020-05-11 14:01
```
...
Successfully installed CairoSVG-2.4.2 Django-2.2.12 O365-2.0.8 Pillow-7.0.0 Pygments-2.5.2 Pyphen-0.9.5 WeasyPrint-51 appdirs-1.4.3 appnope-0.1.0 attrs-19.3.0 backcall-0.1.0 beautifulsoup4-4.9.0 black-19.10b0 boto3-1.12.8 botocore-1.15.8 cairocffi-1.1.0 certifi-2019.11.28 cffi-1.14.0 chardet-3.0.4 click-7.1.1 colorama-0.4.3 cryptography-2.8 cssselect2-0.2.2 cycler-0.10.0 decorator-4.4.1 defusedxml-0.6.0 dj-database-url-0.5.0 django-dotenv-1.4.2 django-extensions-2.2.8 django-mysql-3.3.0 django-rest-knox-4.1.0 django-rest-passwordreset-1.1.0 djangorestframework-3.11.0 docutils-0.15.2 dropbox-9.4.0 et-xmlfile-1.0.1 gunicorn-20.0.4 html5lib-1.0.1 idna-2.9 ipdb-0.12.3 ipython-7.13.0 ipython-genutils-0.2.0 jdcal-1.4.1 jedi-0.17.0 jmespath-0.9.5 kiwisolver-1.1.0 matplotlib-3.1.3 mysqlclient-1.4.6 numpy-1.18.1 oauthlib-3.1.0 openpyxl-3.0.3 pandas-0.25.3 parso-0.7.0 pathspec-0.7.0 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.3 psutil-5.7.0 ptyprocess-0.6.0 pycparser-2.19 pymsteams-0.1.12 pyparsing-2.4.6 python-dateutil-2.8.1 pytz-2019.3 regex-2020.2.20 requests-2.23.0 requests-oauthlib-1.3.0 s3transfer-0.3.3 sentry-sdk-0.14.2 six-1.14.0 soupsieve-2.0 sqlparse-0.3.0 stringcase-1.2.0 stripe-2.43.0 tinycss2-1.0.2 toml-0.10.0 traitlets-4.3.3 typed-ast-1.4.1 tzlocal-2.0.0 urllib3-1.25.8 wcwidth-0.1.8 webencodings-0.5.1 xlrd-1.2.0
$ django-admin startproject abz
$ cd abz
$ vi abz/settings.py
$ ./manage.py shell_plus
# Shell Plus Model Imports
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import Group, Permission, User
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When, Exists, OuterRef, Subquery
from django.utils import timezone
from django.urls import reverse
Python 3.7.7 (default, Mar 10 2020, 15:43:33)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: User
Out[1]: django.contrib.auth.models.User

In [2]:
```

Works fine for me.

Please make sure to test this stuff and verify it's reproducible.
There tons of things that might be "different" or missing in configuration in my sample project making it not fail for me.

Alternatively, if somebody (eg; you are a company who is having this issue in your project) is willing to sponsor this ticket, I can take a look at the project to fix it.
