### ISSUE TITLE
Just found a future deprecation issue

### ISSUE THREAD

**Issue by cnobile2012** [django-extensions/django-extensions#857] opened 2016-03-15 18:48 UTC
/home/cnobile/.virtualenvs/fasbook/local/lib/python2.7/site-packages/django_extensions/management/modelviz.py:307: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  dot = t.render(c)

**Comment by timgraham** [comment] 2016-06-25 02:29
Duplicate of https://github.com/django-extensions/django-extensions/issues/810 (which I believe is fixed).

**Comment by trbs** [comment] 2016-06-25 03:23
thanks !

(if it's not fixed please open a new ticket)

**Closed by trbs** 2016-06-25 03:23 UTC
